/** Generated by scripts/import-house-scenes.cjs. Local sources, never CDN guesses. */
export const HOUSE_SCENE_SOURCES: Readonly<Record<string, number>> = {
  'assets/cloud-balloon-2p.webp': require('@/assets/images/house-scenes/cloud-balloon-2p.webp'),
  'assets/cloud-balloon-4p.webp': require('@/assets/images/house-scenes/cloud-balloon-4p.webp'),
  'assets/cloud-balloon-6p.webp': require('@/assets/images/house-scenes/cloud-balloon-6p.webp'),
  'assets/coral-lagoon-2p.webp': require('@/assets/images/house-scenes/coral-lagoon-2p.webp'),
  'assets/coral-lagoon-4p.webp': require('@/assets/images/house-scenes/coral-lagoon-4p.webp'),
  'assets/coral-lagoon-6p.webp': require('@/assets/images/house-scenes/coral-lagoon-6p.webp'),
  'assets/mushroom-forest-2p.webp': require('@/assets/images/house-scenes/mushroom-forest-2p.webp'),
  'assets/mushroom-forest-4p.webp': require('@/assets/images/house-scenes/mushroom-forest-4p.webp'),
  'assets/mushroom-forest-6p.webp': require('@/assets/images/house-scenes/mushroom-forest-6p.webp'),
  'assets/night-observatory-2p.webp': require('@/assets/images/house-scenes/night-observatory-2p.webp'),
  'assets/night-observatory-4p.webp': require('@/assets/images/house-scenes/night-observatory-4p.webp'),
  'assets/night-observatory-6p.webp': require('@/assets/images/house-scenes/night-observatory-6p.webp'),
};
