/** Generated by scripts/build-house-scene-display.cjs. */
export const HOUSE_SCENE_DISPLAY_SOURCES: Readonly<Record<string, number>> = {
  'assets/cloud-balloon-2p.webp': require('@/assets/images/house-scenes/display/cloud-balloon-2p.png'),
  'assets/cloud-balloon-4p.webp': require('@/assets/images/house-scenes/display/cloud-balloon-4p.png'),
  'assets/cloud-balloon-6p.webp': require('@/assets/images/house-scenes/display/cloud-balloon-6p.png'),
  'assets/coral-lagoon-2p.webp': require('@/assets/images/house-scenes/display/coral-lagoon-2p.png'),
  'assets/coral-lagoon-4p.webp': require('@/assets/images/house-scenes/display/coral-lagoon-4p.png'),
  'assets/coral-lagoon-6p.webp': require('@/assets/images/house-scenes/display/coral-lagoon-6p.png'),
  'assets/mushroom-forest-2p.webp': require('@/assets/images/house-scenes/display/mushroom-forest-2p.png'),
  'assets/mushroom-forest-4p.webp': require('@/assets/images/house-scenes/display/mushroom-forest-4p.png'),
  'assets/mushroom-forest-6p.webp': require('@/assets/images/house-scenes/display/mushroom-forest-6p.png'),
  'assets/night-observatory-2p.webp': require('@/assets/images/house-scenes/display/night-observatory-2p.png'),
  'assets/night-observatory-4p.webp': require('@/assets/images/house-scenes/display/night-observatory-4p.png'),
  'assets/night-observatory-6p.webp': require('@/assets/images/house-scenes/display/night-observatory-6p.png'),
};
